apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-sidecar-injector.fullname" . }}
  labels:
    {{- include "k8s-sidecar-injector.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: |
    {{- $value | toYaml | nindent 4 }}
{{- end }}
