apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-sidecar-injector.fullname" . }}
  labels:
    {{- include "k8s-sidecar-injector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-sidecar-injector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-sidecar-injector.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/admission-webhook: {{ include (print $.Template.BasePath "/admission-webhook.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "k8s-sidecar-injector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "TLS_CERT_FILE"
              value: "/var/lib/secrets/tls.crt"
            - name: "TLS_KEY_FILE"
              value: "/var/lib/secrets/tls.key"
            - name: "LOG_LEVEL"
              value: "2"
            - name: "CONFIG_DIR"
              value: "conf/"
            - name: "CONFIGMAP_LABELS"
              value: "app.kubernetes.io/name={{ include "k8s-sidecar-injector.name" . }},app.kubernetes.io/instance={{ .Release.Name }}"
          ports:
            - name: https
              containerPort: 9443
            - name: metrics
              containerPort: 9000
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: https
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: https
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: webhook-tls
              mountPath: /var/lib/secrets
      volumes:
      - name: webhook-tls
        secret:
          secretName: {{ include "k8s-sidecar-injector.fullname" . }}-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
