{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-sidecar-injector.fullname" . }}
  labels:
    {{- include "k8s-sidecar-injector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-sidecar-injector.fullname" . }}
  labels:
    {{- include "k8s-sidecar-injector.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-sidecar-injector.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-sidecar-injector.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
