apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-sidecar-injector.fullname" . }}
  labels:
    {{- include "k8s-sidecar-injector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  - name: metrics
    port: 80
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "k8s-sidecar-injector.selectorLabels" . | nindent 4 }}
